<?php

namespace Drupal\Tests\trpcultivate_phenotypes\Kernel\Forms;

use Drupal\Tests\tripal_chado\Kernel\ChadoTestKernelBase;
use Drupal\tripal_chado\Database\ChadoConnection;
use Drupal\trpcultivate_phenotypes\Form\TripalCultivatePhenotypesOntologySettingsForm;
use Drupal\Core\Form\FormState;
use Drupal\Core\Link;
use Drupal\Core\Url;
use PHPUnit\Framework\Attributes\RunTestsInSeparateProcesses;

/**
 * Tests associated with TripalCultivatePhenotypesOntologySettingsForm class.
 */
#[RunTestsInSeparateProcesses]
class ConfigOntologyTermsFormTest extends ChadoTestKernelBase {
  /**
   * Modules to enable.
   *
   * @var array
   */
  protected static $modules = [
    'tripal',
    'tripal_chado',
    'trpcultivate_phenotypes',
  ];

  /**
   * Class instance of ontology settings form.
   *
   * @var \Drupal\trpcultivate_phenotypes\Form\TripalCultivatePhenotypesOntologySettingsForm
   */
  protected $ontology_form;

  /**
   * Configuration.
   *
   * @var \Drupal\Core\Config\Config
   */
  private $config;

  /**
   * A Database query interface for querying Chado using Tripal DBX.
   *
   * @var \Drupal\tripal_chado\Database\ChadoConnection
   */
  protected ChadoConnection $chado_connection;

  /**
   * {@inheritdoc}
   */
  protected function setUp(): void {
    parent::setUp();

    // Set test environment.
    \Drupal::state()->set('is_a_test_environment', TRUE);

    // Create a test chado instance as needed by our service.
    $this->chado_connection = $this->createTestSchema(ChadoTestKernelBase::PREPARE_TEST_CHADO);

    // Set genus in the database.
    $test_insert_genus = [
      'Lens',
      'Cicer',
    ];
    $this->chado_connection->insert('1:organism')
      ->fields(['genus', 'species', 'type_id'])
      ->values([
        'genus' => $test_insert_genus[0],
        'species' => 'culinaris',
        'type_id'  => 1,
      ])
      ->values([
        'genus' => $test_insert_genus[0],
        'species' => 'samegenus',
        'type_id'  => 1,
      ])
      ->values([
        'genus' => $test_insert_genus[1],
        'species' => 'arietinum',
        'type_id'  => 1,
      ])
      ->execute();

    // Install module configuration.
    $this->installConfig(['trpcultivate_phenotypes']);

    $this->container = \Drupal::getContainer();

    // Create new instance of the TripalCultivatePhenotypesOntologySettingsForm.
    $this->ontology_form = TripalCultivatePhenotypesOntologySettingsForm::create($this->container);
  }

  /**
   * Tests the form ID.
   */
  public function testGetFormId() {
    $this->assertEquals('trpcultivate_phenotypes_ontology_settings_form', $this->ontology_form->getFormId());
  }

  /**
   * Tests the buildForm method.
   */
  public function testBuildForm() {
    $form = [];
    $form_state = new FormState();

    $this->config = \Drupal::configFactory()->getEditable('trpcultivate_phenotypes.settings');

    // Test with genus set and term values are not set or 0.
    $this->ontology_form->buildForm($form, $form_state);
    $warnings = \Drupal::messenger()->messagesByType('warning');
    $this->assertCount(
      1,
      $warnings,
      "We expect a single warning when simulating no tripal job being executed."
    );

    // Define terms.
    $service_terms = $this->container->get('trpcultivate_phenotypes.terms');
    $service_terms->loadTerms();

    // Test with genus set and term value are set.
    $config_form = $this->ontology_form->buildForm($form, $form_state);

    $this->assertEquals(
      ['trpcultivate_phenotypes/script-autoselect-field'],
      $config_form['#attached']['library'],
      'The attached library of the form generated by buildForm() method does not match expected array.'
    );

    $warnings = \Drupal::messenger()->messagesByType('warning');
    $this->assertCount(
      2,
      $warnings,
      'We expect a warning indicating that the vocabularies cannot be changed once they are uploaded, but there were not any.'
    );

    $this->assertEquals(
      'Tripal Cultivate Phenotypes require that phenotypic traits be housed in
        a Controlled Vocabulary (CV) and pre-define terms used throughout the various processes.
        Use Ontology Terms configuration to setup terms that best support your data.',
      $config_form['description']['#markup'],
      'The description of the form generated by buildForm() method does not match expected markup description.'
    );

    $this->assertEquals(
      'details',
      $config_form['ontology_fieldset']['#type'],
      'The ontology fieldset type of the form generated by buildForm() method does not match expected type.'
    );

    $this->assertEquals(
      Link::fromTextAndUrl('cropontology.org', Url::fromUri('http://www.cropontology.org'))->toRenderable(),
      $config_form['ontology_fieldset']['guide']['#data']['link_02'],
      'The data link 2 on ontology fieldset guide of the form generated by buildForm() method does not match expected link.'
    );
  }

  /**
   * Test validateForm() method.
   */
  public function testValidateForm() {
    // Define terms.
    $service_terms = $this->container->get('trpcultivate_phenotypes.terms');
    $terms = $service_terms->defineTerms();

    // Define genus ontology.
    $service_genusontology = $this->container->get('trpcultivate_phenotypes.genus_ontology');
    $ontology = $service_genusontology->defineGenusOntology();

    // Create form and form state.
    $form = [];
    $form_state = new FormState();

    // Trigger the error when the values in form state is not configured.
    $this->ontology_form->validateForm($form, $form_state);
    $this->assertTrue(
      $form_state->hasAnyErrors(),
      "We expected errors when value is not configured for a term, but there were not any.",
    );

    // Set some values for terms.
    $i = 0;
    foreach ($terms as $key => $value) {
      $form_state->setValue($key, $i);
      $i++;
    }

    // Trigger the error when the configured values do not exist.
    $this->ontology_form->validateForm($form, $form_state);
    $this->assertTrue(
      $form_state->hasAnyErrors(),
      "We expected errors when value configured for a term does not exist, but there were not any.",
    );

    // Trigger the error when configured value is less than or equal to zero.
    foreach ($ontology as $genus => $values) {
      $j = 0;
      foreach ($values as $key => $value) {
        $name = $genus . "_" . $value;
        $form_state->setValue($name, $j);
        $j++;
      }
    }

    $this->ontology_form->validateForm($form, $form_state);
    $this->assertTrue(
      $form_state->hasAnyErrors(),
      "We expected errors when value is set to zero in a form state, but there were not any.",
    );

    // Trigger the error when there are duplicate values.
    $i = 0;
    foreach ($terms as $key => $value) {
      $form_state->setValue($key, $i);
      $i++;
    }
    foreach ($ontology as $genus => $values) {
      $j = 1;
      foreach ($values as $key => $value) {
        $name = $genus . "_" . $value;
        $form_state->setValue($name, $j);
      }
    }
    $this->ontology_form->validateForm($form, $form_state);
    $this->assertTrue(
      $form_state->hasAnyErrors(),
      "We expected errors when there are duplicate trait values in a form state, but there were not any.",
    );
  }

  /**
   * Test submitForm() method.
   */
  public function testSubmitForm() {
    // Define terms.
    $service_terms = $this->container->get('trpcultivate_phenotypes.terms');
    $terms = $service_terms->defineTerms();

    // Define genus ontology.
    $service_genusontology = $this->container->get('trpcultivate_phenotypes.genus_ontology');
    $ontology = $service_genusontology->defineGenusOntology();

    // Create form and form state.
    $form = [];
    $form_state = new FormState();

    // Get the existing cv terms to use.
    $cvterms = $this->chado_connection->query("
      SELECT ct.cvterm_id, CONCAT(ct.name, ' (', db.name, ':', dx.accession, ')')
      FROM {1:cvterm} AS ct LEFT JOIN {1:dbxref} AS dx USING(dbxref_id) LEFT JOIN {1:db} USING(db_id)
      LIMIT 13
    ")
      ->fetchAllKeyed(0, 1);

    $test_cvterms = array_values($cvterms);

    // Set the values to be existing values.
    $i = 0;
    foreach ($terms as $key => $value) {
      $form_state->setValue($key, $test_cvterms[$i]);
      $i++;
    }

    // Set values for genus ontology.
    foreach ($ontology as $genus => $values) {
      $j = 1;
      foreach ($values as $key => $value) {
        $name = $genus . "_" . $value;
        $form_state->setValue($name, $j);
        $j++;
      }
    }

    // Call validateForm() to see if there are any errors.
    $this->ontology_form->validateForm($form, $form_state);
    $this->assertFalse(
      $form_state->hasAnyErrors(),
      'The form state should be valid but there are form errors for some reason.',
    );

    // Call submitForm().
    $this->ontology_form->submitForm($form, $form_state);

    // Test if the Config values are saved properly.
    $config_values = $service_genusontology->getGenusOntologyConfigValues('Lens');
    $this->assertNotNull($config_values, "The genus Ontology Config values are not set properly and returned null");
    $k = 1;
    foreach ($config_values as $key => $value) {
      $this->assertEquals($value, $k, "The genus Ontology Config values are not set properly, so we did not get the expected values.");
      $k++;
    }

    // Test whether the allow new values are saved properly.
    $allow_new = $form_state->getValue('allow_new');
    $config = $this->config('trpcultivate_phenotypes.settings');
    $new_val = $config->get('trpcultivate.phenotypes.ontology.allownew');
    $this->assertEquals($allow_new, $new_val, "Allow new traits are not saved properly.");
  }
}
