<?php

namespace Drupal\Tests\trpcultivate_phenotypes\Kernel;

use Drupal\Core\Form\FormState;
use Drupal\file\Entity\File;
use Drupal\Tests\tripal_chado\Kernel\ChadoTestKernelBase;
use Drupal\trpcultivate_phenotypes\Form\TripalCultivatePhenotypesWatermarkSettingsForm;

/**
 * Class definition ConfigWatermarkFormTest.
 *
 * @coversDefaultClass Drupal\trpcultivate_phenotypes\Form\TripalCultivatePhenotypesWatermarkSettingsForm
 * @group trpcultivate_phenotypes
 */
class ConfigWatermarkFormTest extends ChadoTestKernelBase {

  /**
   * Class instance of watermark controller settings form.
   *
   * @var \Drupal\trpcultivate_phenotypes\Form\TripalCultivatePhenotypesWatermarkSettingsForm
   */
  protected $watermark_form;

  /**
   * Modules to enable.
   *
   * @var array
   */
  protected static $modules = [
    'file',
    'user',
    'system',
    'tripal',
    'tripal_chado',
    'trpcultivate_phenotypes',
  ];

  /**
   * Configuration.
   *
   * @var \Drupal\Core\Config\Config
   */
  protected $config;

  /**
   * {@inheritdoc}
   */
  protected function setUp(): void {
    parent::setUp();

    // Set test environment.
    \Drupal::state()->set('is_a_test_environment', TRUE);

    // Install configurations.
    $this->installConfig(['system', 'trpcultivate_phenotypes']);
    $this->installEntitySchema('file');

    $container = \Drupal::getContainer();

    // Watermark form controller instance.
    $this->watermark_form = new TripalCultivatePhenotypesWatermarkSettingsForm(
      $container->get('file_url_generator'),
      $container->get('entity_type.manager')
    );

    $this->config = $container->get('config.factory');
  }

  /**
   * Test watermark form id matches expected value.
   */
  public function testFormId() {
    $form_id = $this->watermark_form->getFormId();

    // Form id set matches.
    $this->assertEquals(
      'trpcultivate_phenotypes_watermark_settings_form',
      $form_id,
      'The form id returned by getFormId() does not match expected form id value.'
    );
  }

  /**
   * Test buildForm() method.
   */
  public function testBuildForm() {
    $form = [];
    $form_state = new FormState();

    $config_form = $this->watermark_form->buildForm($form, $form_state);

    // Form theme is system configuration type.
    $this->assertEquals(
      'system_config_form',
      $config_form['#theme'],
      'The theme of the form generated by buildForm() method does not match expected theme.'
    );

    // Form has radio button field.
    $this->assertEquals(
      'radios',
      $config_form['charts']['#type'],
      'The form generated by buildForm() method is missing a form field of type radio button.',
    );
  }

  /**
   * Test validateForm() method.
   */
  public function testValidateForm() {
    $form = [];
    $form_state = new FormState();

    // Validate that when choosing to watermark, an image file is required.
    $form_state->setValue('charts', 1);
    $form_state->setValue('file', []);
    $this->watermark_form->validateForm($form, $form_state);
    $this->assertTrue(
      $form_state->hasAnyErrors(),
      'If watermark charts was set to true, then the formValidate() method is expected to trigger an error if no watermark image was provided.'
    );

    $form_state->clearErrors();

    // Validate that when choosing not to watermark, image file is not required.
    $form_state->setValue('charts', 0);
    $form_state->setValue('file', []);
    $this->watermark_form->validateForm($form, $form_state);
    $this->assertFalse(
      $form_state->hasAnyErrors(),
      'If watermark charts was set to false, then the formValidate() method is expected to submit the form without a watermark image.'
    );
  }

  /**
   * Test submitForm() method.
   */
  public function testSubmitForm() {
    $phenotypes_settings = $this->config->getEditable('trpcultivate_phenotypes.settings');
    // The managed_file field is set to upload file into this directory.
    $watermark_dir = $phenotypes_settings->get('trpcultivate.phenotypes.directory.watermark');

    $form = [];
    $form_state = new FormState();

    // Create a test watermark image file.
    $watermark_file = File::create([
      'filename' => 'watermark.png',
      'uri' => $watermark_dir . 'watermark.png',
      'status' => 0,
    ]);

    $watermark_file->save();

    // Allow chart to be watermarked.
    $allow_watermark = 1;

    $form_state->setValue('charts', $allow_watermark);
    $form_state->setValue('file', [$watermark_file->id()]);

    $this->watermark_form->submitForm($form, $form_state);

    // Check the the watermart was set in the configuration for watermark.
    $watermark_config = $phenotypes_settings->get('trpcultivate.phenotypes.watermark');

    $this->assertEquals(
      $watermark_config['charts'],
      $allow_watermark,
      'The watermark configuration for option to watermark all charts must be set to value 1 (watermark all charts).'
    );

    // Reload the file object to pull the lastest update.
    $watermark_file = File::load($watermark_file->id());

    $this->assertEquals(
      $watermark_config['image'],
      $watermark_file->getFileUri(),
      'The watermark image file uri does not match the expected file uri.'
    );
  }

}
