<?php

/**
 * @file
 * Contains all hook implementations for this module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;

/**
 * Implements hook_help().
 *
 * This legacy hook is only run for Drupal < 11, and is replaced by class
 * Drupal\trpcultivate_phenoshare\Hook\TripalCultivatePhenoShareHooks in
 * trpcultivate_phenotshare/src/Hook/TripalCultivatePhenoShareHooks.php.
 */
#[LegacyHook]
function trpcultivate_phenoshare_help($route_name, RouteMatchInterface $route_match) {

  return \Drupal::service('trpcultivate_phenoshare.hooks')
    ->help($route_name, $route_match);
}
