<?php

/**
 * @file
 * Contains all hook implementations for this module.
 */

use Drupal\Core\Cache\RefinableCacheableDependencyInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * This legacy hook is only run for Drupal < 11, and is replaced by class
 * Drupal\trpcultivate_phenotypes\Hook\TripalCultivatePhenotypesHooks in
 * trpcultivate_phenotypes/src/Hook/TripalCultivatePhenotypesHooks.php.
 */
#[LegacyHook]
function trpcultivate_phenotypes_help($route_name, RouteMatchInterface $route_match) {

  return \Drupal::service('trpcultivate_phenotypes.hooks')
    ->help($route_name, $route_match);
}

/**
 * Implements hook_theme().
 *
 * This legacy hook is only run for Drupal < 11, and is replaced by class
 * Drupal\trpcultivate_phenotypes\Hook\TripalCultivatePhenotypesThemeHooks in
 * trpcultivate_phenotypes/src/Hook/TripalCultivatePhenotypesThemeHooks.php.
 *
 * @see /templates
 */
#[LegacyHook]
function trpcultivate_phenotypes_theme($existing, $type, $theme, $path) {

  return \Drupal::service('trpcultivate_phenotypes.theme_hooks')
    ->theme($existing, $type, $theme, $path);
}

/**
 * Implements hook_menu_local_tasks_alter().
 *
 * This legacy hook is only run for Drupal < 11, and is replaced by class
 * Drupal\trpcultivate_phenotypes\Hook\TripalCultivatePhenotypesAlterHooks in
 * trpcultivate_phenotypes/src/Hook/TripalCultivatePhenotypesAlterHooks.php.
 *
 * NOTE: this only removes the delete tab/option. The functionality to
 * delete using the delete entity route may still be used.
 */
#[LegacyHook]
function trpcultivate_phenotypes_menu_local_tasks_alter(&$data, $route_name, RefinableCacheableDependencyInterface &$cacheability) {

  return \Drupal::service('trpcultivate_phenotypes.alter_hooks')
    ->menuLocalTasksAlter($data, $route_name, $cacheability);
}

/**
 * Implements hook_form_alter().
 *
 * This legacy hook is only run for Drupal < 11, and is replaced by class
 * Drupal\trpcultivate_phenotypes\Hook\TripalCultivatePhenotypesAlterHooks in
 * trpcultivate_phenotypes/src/Hook/TripalCultivatePhenotypesAlterHooks.php.
 */
#[LegacyHook]
function trpcultivate_phenotypes_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  return \Drupal::service('trpcultivate_phenotypes.alter_hooks')
    ->formAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_entity_type_alter().
 *
 * This legacy hook is only run for Drupal < 11, and is replaced by class
 * Drupal\trpcultivate_phenotypes\Hook\TripalCultivatePhenotypesAlterHooks in
 * trpcultivate_phenotypes/src/Hook/TripalCultivatePhenotypesAlterHooks.php.
 */
#[LegacyHook]
function trpcultivate_phenotypes_entity_type_alter(array &$entity_types) {

  return \Drupal::service('trpcultivate_phenotypes.alter_hooks')
    ->entityTypeAlter($entity_types);
}

/**
 * Tripal Job callback.
 *
 * Job registered during install to insert terms used by configuration
 * page default field values.
 *
 * @see config/trpcultivate_phenotypes.settings
 */
function trpcultivate_phenotypes_install_ontologyterms() {

  // We need the schema to ensure we are inserting into the right one.
  $connection = \Drupal::service('tripal_chado.database');
  $schema = $connection->getSchemaName();

  // Create terms defined in config entity.
  \Drupal::service('trpcultivate_phenotypes.terms')
    ->loadTerms($schema);

  // Create genus-ontology configuration.
  \Drupal::service('trpcultivate_phenotypes.genus_ontology')
    ->loadGenusOntology();
}
