<?php

/**
 * @file
 * Contains all hook implementations for this module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_help().
 */
function trpcultivate_phenotypes_help($route_name, RouteMatchInterface $route_match) {

  switch ($route_name) {
    // Provides the module overview in the help tab.
    case 'help.page.trpcultivate_phenotypes':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';

      $output .= '<ul><li>' . t('Creates genus-specific Tripal Content Types for Trait pages to provide a landing page for all information about a specific trait. These are specific to the genus to ensure that all data summarized is relevant and to respect that traits to vary between genus in their expression and specific definition.') . '</li>'
        . '<li>' . t('Supports using genus-specific ontologies to ensure you capture each trait fully and mapping of these genus-specific terms to domain and system specific ontologies to enable comparison and data sharing.') . '</li>'
        . '<li>' . t('Focuses on the Trait - Method - Unit formula for describing phenotypic data.') . '</li>'
          . '<ul>
               <li>' . t('This supports collecting all data for a specific trait (e.g. Plant Height) into a single page while still fully describing methodology and units for accurate analysis.') . '</li>'
            . '<li>' . t('For the Plant Height trait, you would have data available for multiple experiments, measurement methodology (e.g highest canopy point, average canopy height in a plot, drone captured height based on NDVI) and units on the same page but they would not be combined across experiment, method or units.') . '</li>
          </ul>'
        . '<li>' . t('A holding space for raw phenotypic data / measurements right after collection which is private by default and sharable with individual accounts. These data are kept outside the main schema for your biological data since they are raw, unpublished results. There is an easy means to backup data, validate and import by season.')
        . '</li>
        </ul>';

      return $output;

    default:
  }
}

/**
 * Tripal Job callback.
 *
 * Job registered during install to insert terms used by configuration
 * page default field values.
 *
 * @see config/trpcultivate_phenotypes.settings
 */
function trpcultivate_phenotypes_install_ontologyterms() {

  // We need the schema to ensure we are inserting into the right one.
  $connection = \Drupal::service('tripal_chado.database');
  $schema = $connection->getSchemaName();

  // Create terms defined in config entity.
  \Drupal::service('trpcultivate_phenotypes.terms')
    ->loadTerms($schema);

  // Create genus-ontology configuration.
  \Drupal::service('trpcultivate_phenotypes.genus_ontology')
    ->loadGenusOntology();
}

/**
 * Implements hook_theme().
 *
 * @see /templates
 */
function trpcultivate_phenotypes_theme($existing, $type, $theme, $path) {
  $items = [];

  $items = [
    // Theme instructions found in the header section
    // of ontology configuration page.
    'header_instructions' => [
      'variables' => [
        'data' => [
          'section' => '',
          'link_01' => '',
          'link_02' => '',
        ],
      ],
      'template' => 'trpcultivate-phenotypes-template-header-instructions',
    ],
  ];

  return $items;
}

/**
 * Implements hook_menu_local_tasks_alter().
 *
 * NOTE: this only removes the delete tab/option. The functionality to
 * delete using the delete entity route may still be used.
 */
function trpcultivate_phenotypes_menu_local_tasks_alter(&$menu_tasks) {

  // Remove the Delete tab if research experiment has phenotypes.
  // Apply this delete tab restriction to the following Tripal content types.
  $content_types = [
    'research_experiment',
  ];

  $page_parameters = \Drupal::service('current_route_match')
    ->getParameters();

  if ($tripal_entity = $page_parameters->get('tripal_entity')) {
    if (in_array($tripal_entity->bundle(), $content_types)) {
      $research_experiment = $tripal_entity->get('exp_name')->getValue()[0];

      $has_pheno = \Drupal::service('database')
        ->select('trpcultivate_phenocombo', 'tc')
        ->condition('tc.project_id', $research_experiment['record_id'], '=')
        ->countQuery()
        ->execute()
        ->fetchField();

      if ($has_pheno) {
        $menu_tasks['tabs'][0]['entity.tripal_entity.delete_form'] = [];
      }
    }
  }
}

/**
 * Implements hook_entity_presave().
 *
 * Enforces genus-phenotypes relationship when providing genus to Research
 * Experiment entity.
 */
function trpcultivate_phenotypes_tripal_entity_presave(EntityInterface $entity) {

  if ($entity->bundle() == 'research_experiment') {
    $experiment_id = $entity->get('exp_name')->getValue()[0]['record_id'];

    // Genus as provided in the Design/Germplasm/Germplasm Genus field.
    $exp_germgenus = array_column(
      $entity->get('exp_germgenus')->getValue(),
      'value'
    );

    // All genus configured in Phenotypes.
    $genus_ontology_service = \Drupal::service('trpcultivate_phenotypes.genus_ontology');
    $pheno_configgenus = $genus_ontology_service->getConfiguredGenusList();

    $chado_connection = \Drupal::service('tripal_chado.database');

    if ($pheno_configgenus) {
      foreach ($pheno_configgenus as $genus) {
        $genus_trait_config = $genus_ontology_service
          ->getGenusOntologyConfigValues($genus)['trait'];

        $query = $chado_connection->select('trpcultivate_phenocombo', 'tp');
        $query->join('1:cvterm', 't', 'tp.attr_id = t.cvterm_id');
        $query->join('1:cv', 'v', 't.cv_id = v.cv_id');

        // A phenotype to a genus would suffice enforcement check.
        $has_pheno = $query
          ->fields('tp', ['combo_id'])
          ->condition('tp.project_id', $experiment_id, '=')
          ->condition('v.cv_id', $genus_trait_config, '=')
          ->range(0, 1)
          ->execute()
          ->fetchField();

        // Genus has phenotypes and is missing from the list of genus of the
        // research experiment entity.
        if ($has_pheno > 0 && !in_array($genus, $exp_germgenus)) {
          throw new \Exception('Genus ' . $genus . ' of this research experiment is linked to Phenotypes module. Please restore the genus and try again.');
        }
      }
    }
  }
}
