<?php

namespace Drupal\trpcultivate_phenotypes\Controller;

use Drupal\Core\Controller\ControllerBase;
use Drupal\Core\Extension\ModuleHandlerInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Class definition TripalCultivatePhenotypesSettingsController.
 *
 * Controller to display a dashboard page that houses links and descriptions
 * to configuration pages.
 */
class TripalCultivatePhenotypesSettingsController extends ControllerBase {

  /**
   * Module hander service.
   *
   * @var \Drupal\Core\Extension\ModuleHandlerInterface
   */
  protected $module_handler;

  /**
   * Constructor.
   *
   * @param \Drupal\Core\Extension\ModuleHandlerInterface $module_handler
   *   The module handler service.
   */
  public function __construct(ModuleHandlerInterface $module_handler) {
    $this->module_handler = $module_handler;
  }

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container) {
    return new static(
      $container->get('module_handler')
    );
  }

  /**
   * Provides an administrative list of phenotypes configuration pages.
   *
   * @return array
   *   A render array consisting of a details element for each configuration
   *   page where the title is the configuration section and the contents
   *   include a short description plus a link.
   */
  public function loadPage() {
    // Quick enabled or disabled status of sub-phenotypes modules and report
    // to dashboard.
    $status_message = 'Tripal Cultivate Phenotypes Modules Status: ';

    foreach (['trpcultivate_phenoshare', 'trpcultivate_phenocollect'] as $m) {
      $is_enabled = ($this->module_handler->moduleExists($m)) ? 'is enabled' : 'is disabled';
      $status_message .= '*' . $m . ' ' . $is_enabled . ' ';
    }

    $url = Url::fromUri('internal:/admin/modules');
    $link = Link::fromTextAndUrl('Manage Modules', $url)
      ->toString();

    $this->messenger()->addStatus($status_message . ' - ' . $link);

    // Describe R Rules configuration:
    $url = Url::fromRoute('trpcultivate_phenotypes.settings_r');
    $link = Link::fromTextAndUrl($this->t('Click here'), $url)
      ->toString();

    $describe = 'Tripal Cultivate Phenotypes supports R language for statistical computing by providing
      syntactically valid version of trait or values. Use R Transformation Rules configuration page to define
      standard transformation rules to apply to trait or string when converting to R version.';

    $element['rrules'] = [
      '#type' => 'details',
      '#title' => $this->t('R TRANSFORMATION RULES'),
      '#description' => $this->t('@describe<br>@link', ['@describe' => $describe, '@link' => $link]),
      '#open' => TRUE,
    ];

    // Describe Watermarking configuration:
    $url = Url::fromRoute('trpcultivate_phenotypes.settings_watermark');
    $link = Link::fromTextAndUrl($this->t('Click here'), $url)
      ->toString();

    $describe = 'Every diagram generated by Tripal Cultivate Phenotypes can be superimposed with personalized
      logo or text logo to ensure proper credit and indicate authenticity. Use Watermark Chart configuration
      to set watermarking scheme of modules.';

    $element['watermarking'] = [
      '#type' => 'details',
      '#title' => $this->t('WATERMARK CHART'),
      '#description' => $this->t('@describe<br>@link', ['@describe' => $describe, '@link' => $link]),
      '#open' => TRUE,
    ];

    // Describe Ontologies configuration:
    $url = Url::fromRoute('trpcultivate_phenotypes.settings_ontology');
    $link = Link::fromTextAndUrl($this->t('Click here'), $url)
      ->toString();

    $describe = 'Tripal Cultivate Phenotypes require that phenotypic traits be housed in a Controlled Vocabulary (CV)
      and pre-define terms used throughout the various processes. Use Ontology Terms configuration to setup terms that
      best support your data.';

    $element['ontologies'] = [
      '#type' => 'details',
      '#title' => $this->t('ONTOLOGY TERMS'),
      '#description' => $this->t('@describe<br>@link', ['@describe' => $describe, '@link' => $link]),
      '#open' => TRUE,
    ];

    return $element;
  }

}
