<?php

namespace Drupal\Tests\trpcultivate_phenotypes\Unit;

use Drupal\Core\DependencyInjection\ContainerBuilder;
use Drupal\Core\Config\Config;
use Drupal\Core\Config\ConfigFactoryInterface;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\File\FileUrlGenerator;
use Drupal\Core\Form\FormState;
use Drupal\Core\Messenger\MessengerInterface;
use Drupal\Core\StringTranslation\TranslationInterface;
use Drupal\Tests\UnitTestCase;
use Drupal\trpcultivate_phenotypes\Form\TripalCultivatePhenotypesWatermarkSettingsForm;

/**
 * Class definition ConfigWatermarkFormTest.
 *
 * @coversDefaultClass Drupal\trpcultivate_phenotypes\Form\TripalCultivatePhenotypesWatermarkSettingsForm
 * @group trpcultivate_phenotypes
 */
class ConfigWatermarkFormTest extends UnitTestCase {

  /**
   * Class instance of watermark controller settings form.
   *
   * @var \Drupal\trpcultivate_phenotypes\Form\TripalCultivatePhenotypesWatermarkSettingsForm
   */
  protected $watermark_form;

  /**
   * {@inheritdoc}
   */
  protected function setUp(): void {
    parent::setUp();

    // Mock file url generator.
    $mock_file_url_generator = $this->createMock(FileUrlGenerator::class);
    // Mock file entity manager.
    $mock_file_entity_manager = $this->createMock(EntityTypeManagerInterface::class);
    // Mock configuration.
    $watermark_config_mock = $this->prophesize(Config::class);
    $watermark_config_mock->get('trpcultivate.phenotypes.watermark')
      ->willReturn([
        'charts' => FALSE,
        'image' => NULL,
        'file_ext' => ['png', 'gif'],
      ]);
    $watermark_config_mock->get('trpcultivate.phenotypes.directory.watermark')
      ->willReturn('public://TripalCultivatePhenotypes/watermark/');

    $all_config_mock = $this->prophesize(ConfigFactoryInterface::class);
    $all_config_mock->getEditable('trpcultivate_phenotypes.settings')
      ->willReturn($watermark_config_mock);

    // Isolated configuration for watermark configuration.
    $watermark_config = $all_config_mock->reveal();

    $this->watermark_form = new TripalCultivatePhenotypesWatermarkSettingsForm($mock_file_url_generator, $mock_file_entity_manager, $watermark_config);

    // Mock translation interface.
    $mock = $this->prophesize(TranslationInterface::class);
    $translation = $mock->reveal();
    $this->watermark_form->setStringTranslation($translation);
    // Mock messenger interface.
    $mock = $this->prophesize(MessengerInterface::class);
    $messenger = $mock->reveal();
    $this->watermark_form->setMessenger($messenger);

    $container = new ContainerBuilder();
    $container->set('config.factory', $watermark_config);
    \Drupal::setContainer($container);
  }

  /**
   * Test watermark form id matches expected value.
   */
  public function testFormId() {
    $form_id = $this->watermark_form->getFormId();

    // Form id set matches.
    $this->assertEquals(
      'trpcultivate_phenotypes_watermark_settings_form',
      $form_id,
      'The form id returned by getFormId() does not match expected form id value.'
    );
  }

  /**
   * Test buildForm() method.
   */
  public function testBuildForm() {
    $form = [];
    $form_state = new FormState();

    $config_form = $this->watermark_form->buildForm($form, $form_state);

    // Form theme is system configuration type.
    $this->assertEquals(
      'system_config_form',
      $config_form['#theme'],
      'The theme of the form generated by buildForm() method does not match expected theme.'
    );

    // Form has radio button field.
    $this->assertEquals(
      'radios',
      $config_form['charts']['#type'],
      'The form generated by buildForm() method is missing a form field of type radio button.',
    );
  }

  /**
   * Test validateForm() method.
   */
  public function testValidateForm() {
    $form = [];
    $form_state = new FormState();

    // Validate that when choosing to watermark, an image file is required.
    $form_state->setValue('charts', 1);
    $form_state->setValue('file', []);
    $this->watermark_form->validateForm($form, $form_state);
    $this->assertTrue(
      $form_state->hasAnyErrors(),
      'If watermark charts was set to true, then the formValidate() method is expected to trigger an error if no watermark image was provided.'
    );

    $form_state->clearErrors();

    // Validate that when choosing not to watermark, image file is not required.
    $form_state->setValue('charts', 0);
    $form_state->setValue('file', []);
    $this->watermark_form->validateForm($form, $form_state);
    $this->assertFalse(
      $form_state->hasAnyErrors(),
      'If watermark charts was set to false, then the formValidate() method is expected to submit the form without a watermark image.'
    );
  }

}
